# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-22 00:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='crice',
            new_name='price',
        ),
    ]
